# Generated by Django 5.1.7 on 2025-03-26 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planora_app', '0002_project_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Assigned', 'Assigned'), ('In Progress', 'In Progress'), ('Review', 'Review'), ('Completed', 'Completed')], default='Assigned', max_length=20),
        ),
    ]
