# Generated by Django 5.1.7 on 2025-03-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planora_app', '0006_task_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='task',
            name='start_time',
        ),
        migrations.AddField(
            model_name='task',
            name='elapsed_time',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
