# Generated by Django 5.1.7 on 2025-03-28 09:51

import planora_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planora_app', '0008_taskcomment_taskfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskfile',
            name='file',
            field=models.FileField(upload_to=planora_app.models.task_file_upload_path),
        ),
    ]
