# Generated by Django 5.1.7 on 2025-03-28 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planora_app', '0009_alter_taskfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
