# Generated by Django 5.1.7 on 2025-04-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planora_app', '0012_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('manager', 'manager'), ('developer', 'developer')], max_length=20),
        ),
    ]
