# Generated by Django 5.1.7 on 2025-04-16 08:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planora_app', '0013_alter_notification_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcomment',
            name='reactions',
            field=models.ManyToManyField(blank=True, related_name='comment_reactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
